### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by madvas** [district0x/name-bazaar#1]
![home page](https://user-images.githubusercontent.com/3857155/29237047-1c61b470-7f40-11e7-8c67-d6bf1b1c2cc2.png)

**Comment by AMOz1** [comment]
I have a general question... will listing and purchasing the names require MetaMask plugin?
how about on mobile...how will one connect to ethereum network on mobile?

**Comment by madvas** [comment]
Listing and purchasing will require MetaMask/Parity/Mist, but just viewing data won't require it. Therefore viewing on mobile will work. Later, when [Status](http://status.im/) gets on mainnet, creating offerings/purchasing will be possible from mobile as well.

**Comment by AMOz1** [comment]
I see.. makes sense
so.. when somebody purchases my domain name... the funds will go directly to the address that listed that name... or.. will I have one address in my settings and all the funds will go there?

**Comment by madvas** [comment]
It'll go directly to address from which you created listing

**Comment by AMOz1** [comment]
ok... one more

is the ownership of listed domain temporarily transferred to name-bazaar address ..and then to the new owner ...probably..I guess... because you need to be able to transfer the domain name to new owner without my explicit approval.

aha... is there any timeline for when can we expect this to be released? :)

**Comment by madvas** [comment]
yes, ownership is temporarily transferred to offering contract. Each offering is separate smart-contract. Then, the name is transferred to a new owner without your explicit approval. We expect release in about 2 months.

**Comment by imdying** [comment]
design feedback:
Numbers should be right aligned.
Main options should be buy, sell, faq/help 

Will it be possible to provide ux feedback before launch?

**Comment by madvas** [comment]
yeah, good points. Home page design needs more love definitely. We'll be discussing it soon with our design company

**Comment by happyrobotstudio** [comment]
The green, purple and yellow colour choice for https://namebazaar.io/ is nice, quite bold and 'dApp' like .. gives me the visual indication this is not just another web app ,, 

Looking forward to seeing how the colours evolve into the homepage design

Cheers!
