### ISSUE TITLE
Offering Details Page

### ISSUE THREAD

**Issue by madvas** [district0x/name-bazaar#10]
![offering details](https://user-images.githubusercontent.com/3857155/29237102-40cb7cf0-7f41-11e7-9267-f25fdf2beae2.png)

**Comment by sam1210** [comment]
PC -Why are the "highest bid" and "num of bids" on the right side?  I'm concerned that the positions "highest bid" ,"num of bids" and "time remaining" are different.Cuz those are important info. so it should collect in one place.please tell me if there is an reason.
I think tablet is perfect.

**Comment by madvas** [comment]
Well, the thinking is: since "higest bid" and "num if bids" are important, should be visually separated from the rest of text. Could be also placed in the middle, similarly to time-remaining, but I found this variant more elegant and space-saving. Probably will try both variants once page is done and see which one looks better.

**Comment by sam1210** [comment]
thx reply. I hope that we will found perfect position.

**Comment by chasecattaneo** [comment]
Would like to see "number of views" for each listing

**Comment by imdying** [comment]
Not sure i understand why number of bids is that important...

**Comment by madvas** [comment]
Well number of bids shows which auctions are "hot" right now, so user can quickly find them
