### ISSUE TITLE
Transaction Log

### ISSUE THREAD

**Issue by madvas** [district0x/name-bazaar#11]
![transaction log](https://user-images.githubusercontent.com/3857155/29237110-645c1f08-7f41-11e7-940e-d341a28bd714.png)

**Comment by mediolateral** [comment]
Looks like a popup, what's the workflow to get here? Would be ideal to not have popups which are difficult to close. Tiny x's are bad.

Clean and simple! The status and larger font and simple descriptions are great.

**Comment by madvas** [comment]
This is when you click on Bell icon in top right corner. Shows your history of your transactions. Similar to MetaMask's log, but this one is more optimised for our dapp with human friendly descriptions and be able go to relevant page after clicking on it.

**Comment by mediolateral** [comment]
Ah thanks!
