### ISSUE TITLE
My Settings Page

### ISSUE THREAD

**Issue by madvas** [district0x/name-bazaar#12]
![my settings](https://user-images.githubusercontent.com/3857155/29237122-83c12172-7f41-11e7-80bf-e9d3a6319554.png)

**Comment by mediolateral** [comment]
Question on the navigation - When i'm updating my settings I need to be able to go back to the main screen if I want to cancel.

Maybe at the top replace the options menu with just a back arrow. You could save lot's of space at the top as well by having: "<- My Settings"; the bell could stay.

**Comment by madvas** [comment]
No sure what you mean by "go back to the main screen if I want to cancel". Cancelling submitted transaction is not possible by Ethereum's nature. You can always go back where you were by browser native back button

**Comment by puttersworth** [comment]
My understanding is that you will be able to sell "names" for ETH, therefore, would this be a good place for an input field to enter a preferred ETH address for where people would like that ETH sent to? Please correct me if this is not right.
