### ISSUE TITLE
Creating offering and transferring ownership in a single tx

### ISSUE THREAD

**Issue by madvas** [district0x/name-bazaar#177]
Now that ENS is using ERC721, we should be able to create an offering and transfer offered name into the offering contract within a single transaction, which wasn't previously possible. 

Steps to implements this would go as follows: 
1. When user clicks Create Offering it would call `safeTransferFrom` of ENS ERC721
2. `OfferingFactory` contract would be extended with `IERC721Receiver` implementing `onERC721Received` callback
3. The callback would call `createOffering` which, besides other things, would transfer the ERC721 ownership from the factory contract into the actual offering contract. 

So this should save user 1 transaction of manually transferring ERC721 ownership into an offering contract.

**Comment by ladislavdubravsky** [comment]
Right, but this will work only with top level names traded over ethregistrar. Names in ensregistry itself are still not ERC721 as far as I see, and subnames have no other governance mechanism in general.

**Comment by madvas** [comment]
I see, okay so if it works just for top-level names that's alright. For non ERC721 names, if it works as we have it now, that's alright too.
