### ISSUE TITLE
Edit expired auction shows blank page

### ISSUE THREAD

**Issue by madvas** [district0x/name-bazaar#194]
When I want to edit auction that finished and had no bids, page shows as blank: 
https://namebazaar.qa.district0x.io/offerings/0x06ae6a2af6e98bff0247e9c295544eb420518618/edit

![image](https://user-images.githubusercontent.com/3857155/121633978-00b64e80-caae-11eb-8d79-d7d602bed672.png)

**Comment by ladislavdubravsky** [comment]
I believe this is a part of a more general issue. Compare https://github.com/vacuumlabs/name-bazaar/issues/59.

**Comment by ladislavdubravsky** [comment]
Ok I was wrong, this one is a very specific problem and I wasn't able to replicate the other one. I will create a PR for this issue only.
