### ISSUE TITLE
Search Offerings Page

### ISSUE THREAD

**Issue by madvas** [district0x/name-bazaar#2]
![offerings](https://user-images.githubusercontent.com/3857155/29237054-4bd8691a-7f40-11e7-8236-503eca8bdb76.png)

**Comment by mediolateral** [comment]
Device (left) - list screen could have icons for bids & time make it a bit easier for the eye to immediately be drawn to bids vs. time. Good otherwise.

Device (right) - how to cancel/go back? looks decent, a lot of tick boxes maybe can rethink that somehow

**Comment by madvas** [comment]
> Device (left) - list screen could have icons for bids & time make it a bit easier for the eye to immediately be drawn to bids vs. time. Good otherwise.

Fair point, but can't think of really intuitive icons for that. Open for suggestions.

> Device (right) - how to cancel/go back? looks decent, a lot of tick boxes maybe can rethink that somehow

You can swipe it back right, or tap on left uncovered area

**Comment by jfrag** [comment]
if you make an infinite scroll, it is complicate to modify the form no ?
Idea: put the searching form on the right in sticky mode

https://codepen.io/ChaseMarcum/full/EaVVYG

**Comment by madvas** [comment]
I plan to include scroll to top button. The reason I'd rather avoid sticky filtering menu in this case is because when you change some filter options, results are changed, therefore it bumps you back to the top anyway. It can be weird jumping in UI.

**Comment by veqtor** [comment]
Looks great, keep it like this!

**Comment by imdying** [comment]
To provide Visual feedback on each auction it's background could have a progress bar, or a bar underneath, showing % of auction with indicators for each bid. 

If you could autoextend autions if a bid is placed in the last minute thatd be great. Trademe.co.nz is an auction site with a great user interface.

**Comment by madvas** [comment]
Yes auctions have functionality to autoextend. That's what Time Extension setting is for.
