### ISSUE TITLE
Suggestion form audit: Unnecessary complication due to transferPrice parameter to AuctionOffering.finalize

### ISSUE THREAD

**Issue by madvas** [district0x/name-bazaar#28]
Implement changes related to following point from audit: https://gist.github.com/Arachnid/3416e5a85b5b67eb9cdfa2252a5e28d9#unnecessary-complication-due-to-transferprice-parameter-to-auctionofferingfinalize

We can remove [transferPrice](https://github.com/district0x/name-bazaar/blob/master/resources/public/contracts/src/AuctionOfferingLibrary.sol#L123) parameter and instead make fallback automatic. To do so, we'll use Solidity's `send` function instead of `transfer`. 
`send` function doesn't throw error if transacting fails, but returns false. 
So instead of this
```
if (transferPrice) {
    offering.originalOwner.transfer(offering.price);
} else {
    self.pendingReturns[offering.originalOwner] =
    self.pendingReturns[offering.originalOwner].add(offering.price);
```
We'll write this: 
```
if (!offering.originalOwner.send(offering.price)) {
    self.pendingReturns[offering.originalOwner] =
    self.pendingReturns[offering.originalOwner].add(offering.price);    
}
```

In similar fashion we can edit [bid](https://github.com/district0x/name-bazaar/blob/master/resources/public/contracts/src/AuctionOfferingLibrary.sol#L48) function, where  funds will be tried to sent to overbid user instantly and only after that fails, we'll put it into pending returns. Tests will need to be edited, that instead of pending returns it checks user's balance if overbid amount was returned. 
Testing fallback pending returns scenario would be pretty tricky, it would require creating contract with fallback function that always fails and bid through this contract. I'd leave implementations of this after release, as we have more important tasks to do first.

**Comment by wambat** [comment]
@madvas , there is a usecase: "If user has bid before, it's enough for him to send only difference needed for next bid." . Is this situation handled correctly by UI, like, does it have an information what amount is sufficient for user to place his next bid? Maybe some kind of event should be fire to distinguish these two sitations, when funds were transfered successful, and when they were not, in order to maintain syncronisation with the cache db?

**Comment by madvas** [comment]
@wambat Good point. It is more n less handled in UI, but you know what, let's ditch all this reusing of pending returns. It's unnecessary complicating things. Nick suggested it also. 
So amount in pending returns is never used for next bid. Not even in self overbidding. The amount user sends is the amount of bid, no special tricks. If user tries to overbid himself, simply contract will try to send him previous bid back, if that fails, adds it into pending returns.

**Comment by madvas** [comment]
cache db doesn't really need to know about whether funds were transferred or sticking in pending returns. It's not relevant for search. And UI is listening to any changes to offering and reloads whole offering if anything changes, including user's pending returns, so that's ok too.
