### ISSUE TITLE
Requests Page

### ISSUE THREAD

**Issue by madvas** [district0x/name-bazaar#3]
![offering requests](https://user-images.githubusercontent.com/3857155/29237058-6feca398-7f40-11e7-9ddd-4f95b9fb182a.png)

**Comment by AMOz1** [comment]
I must say I don't understand "request" button... what can I request here?

**Comment by madvas** [comment]
With "request" you signal an owner out there that there's a demand for that name. Also, if in My Settings you associate email address with your Ethereum address, you'll get email notification once the requested name comes on sale.

**Comment by madvas** [comment]
yes, requests are for names not listed on NameBazaar yet
