### ISSUE TITLE
Watched Names Page

### ISSUE THREAD

**Issue by madvas** [district0x/name-bazaar#4]
![watched names](https://user-images.githubusercontent.com/3857155/29237063-9488aa12-7f40-11e7-90b4-40b69ac417e6.png)

**Comment by mediolateral** [comment]
looks good, particularly the mobile view. consider the icons for bid/time left stacked on top of each other as mentioned preivously

**Comment by madvas** [comment]
I'm intentionally keeping full width reserved for name, because names can be pretty long

**Comment by mediolateral** [comment]
okay good point, apologies for not considering that!
