### ISSUE TITLE
Internal smart-contract audit + adding 1 test scenario

### ISSUE THREAD

**Issue by madvas** [district0x/name-bazaar#45]
In commit https://github.com/district0x/name-bazaar/commit/59bd456742507452c8a9cd7e056dc73203839213 were addressed all outstanding issues from [audit](https://gist.github.com/Arachnid/3416e5a85b5b67eb9cdfa2252a5e28d9). 

Could you please perform small audit on contracts before we send it back to Nick for final look. Also please add 1 new test scenario I'll describe below. 

Issues that were addressed: 
#### Dispatcher pattern is obsoleted by Byzantium
Now we use very thin proxy contract Forwarder, which proxies all functions to deployed instance of BuyNowOffering.sol or AuctionOffering.sol, which are singletons used only for logic, not storing data. You can read more about this pattern [here](https://blog.zeppelin.solutions/proxy-libraries-in-solidity-79fbe4b970fd) 

#### Use of require instead of modifiers
Since we don't use Solidity's libraries, we can use modifiers in offering contract.

#### Use of 'address' instead of strongly-typed alternatives
This has been changed throughout the app

#### Storage of duplicate data
This was solved by putting placeholders into offering contracts, which will be replaced after compilation. This way those addresses don't have to be set on contract initialisation run by user, therefore user doesn't have to pay gas for it. 

#### Bid value is implicit
This was solved by removing reusing pending returns for new bids

#### Hardcoding of ENS registrar address
Instead of passing registrar contract address, now we access it's address by ens.owner(namehash("eth")), which should stay up to date even if registrar address changes in the future. 

#### Winning bidder can claim both name and funds with emergency multisig assistance
This was solved by adding `onlyWithoutNewOwner` into `reclaimOwnership` function. 

#### Emergency intervention requires time-critical operations on every open offering
Offering registry has now variable `isEmergencyPaused`, which can disable buy/bid/finalize function on all offerings at once. Please write test scenario when `isEmergencyPaused` is used.

**Comment by wambat** [comment]
Why can't offering registry remove offerings? So it won't be visible in the offering list?

**Comment by wambat** [comment]
Why `onlyWhenNotEmergencyPaused` is not used in every publicly avail calls, like withdraw? Shouldn't we freeze the contract entirely for emergency maintanance.

**Comment by wambat** [comment]
https://github.com/district0x/name-bazaar/commit/59bd456742507452c8a9cd7e056dc73203839213#commitcomment-25059903 - docstring seems misleading

**Comment by madvas** [comment]
1. Well, we can't uncall onOfferingAdded event. 
2. Mostly because we want to be able to load offering data even when it's finished. So we can display user's history in My Offerings, My Purchases pages, etc.
