### ISSUE TITLE
Create Offering Page

### ISSUE THREAD

**Issue by madvas** [district0x/name-bazaar#5]
![create offering](https://user-images.githubusercontent.com/3857155/29237069-bc513960-7f40-11e7-9c0f-f21557de9e58.png)

**Comment by AMOz1** [comment]
...maybe there should be an option for seller to add short comment or description to the name offering

**Comment by imdying** [comment]
Minimum reserve + buy now price should be possible at the same time... as long as buy now is higher than minimum reserve..

**Comment by madvas** [comment]
Not sure what you mean by minimum reserve. You mean combine Auction and Buy Now together?

**Comment by imdying** [comment]
>You mean combine Auction and Buy Now together?

yes. check out how the auctions work on trademe.co.nz it's a great system


https://www.trademe.co.nz/sports/cycling/other-bikes/auction-1419626519.htm
