### ISSUE TITLE
My Offerings / User's Offerings Page

### ISSUE THREAD

**Issue by madvas** [district0x/name-bazaar#6]
![my offerings _ user s offerings](https://user-images.githubusercontent.com/3857155/29237075-d2df9866-7f40-11e7-8b04-cce69c837d36.png)

**Comment by mediolateral** [comment]
excellent. icons for the bids/time left in mobile view would be good (stacked on top of each other). maybe even on the web view

**Comment by chasecattaneo** [comment]
It would be great if there was a share link on this page for sharing your offerings on social media or anything else preferred. Will lead to more traffic on the site.

**Comment by chasecattaneo** [comment]
You can share your full list of offerings or a single offering..

**Comment by chasecattaneo** [comment]
Also would really like to see the number of views for each offering.. will help determine the popularity

**Comment by madvas** [comment]
yep, share buttons are sure good idea. There are user's offerings page as well as offering detail page, so those can be shared.

**Comment by chasecattaneo** [comment]
Thanks.. how about the number of views feature too?

**Comment by imdying** [comment]
"Offerings" is not a very good word. Maybe "selling"?

Also "past offerings" could be "history". Current offerings shouldn't be an option. It should default to current sales plus sales in the last month.  That's what people are going to be looking for.
