### ISSUE TITLE
Add Trezor Support

### ISSUE THREAD

**Issue by Astrantia** [district0x/name-bazaar#67]
I just realized I hold all my ENS domains on my trezor wallets. Trezor users can't use metamask and even if we could export our keys, we would rather not. Namebazaar needs to be supporting hardware wallets too.
I guess explicitly supporting Trezor isn't necessary as far as you provide us with the contract addresses and ABI's to interact with contracts without the website.

**Comment by madvas** [comment]
Doesn't Parity support Trezor? Supporting hardware wallets is rather role of MetaMask and Parity I think. Anyways, our ABIs are here in case you wanted: https://github.com/district0x/name-bazaar/tree/master/resources/public/contracts/build

**Comment by sulkhanp** [comment]
Currently, neither parity nor metamask support Trezor. Don't we need to know the corresponding addresses for contracts to be able to access them in MEW?

**Comment by madvas** [comment]
Depends what you actually wanna do. I think simpler would be actually to transfer your name from Trezor to some MetaMask address via MEW and then continue using NameBazaar. To Transfer ownership you use following setup in MEW

![image](https://user-images.githubusercontent.com/3857155/31957091-c39ec5d2-b917-11e7-84e7-298d7fbecba5.png)
