### ISSUE TITLE
My Purchases / User's Purchases Page

### ISSUE THREAD

**Issue by madvas** [district0x/name-bazaar#7]
![my purchases](https://user-images.githubusercontent.com/3857155/29237088-f2c7435e-7f40-11e7-9614-93de511b684c.png)

**Comment by imdying** [comment]
don't need the "bought for" that's pretty obvious. Also right align the price. 

Get rid of drop down and have sortable purchase date column. Default to latest.

**Comment by madvas** [comment]
Yeah, "bought for" can be probably removed. I'd keep drop down tho, because there might be sorting options that are not really a column. Also this way it's more consistent across site.
