### ISSUE TITLE
Force Character Count To Be 7

### ISSUE THREAD

**Issue by sulkhanp** [district0x/name-bazaar#71]
I think this needs to be fixed, because right now people think you can have ENS names like one.eth, dog.eth, wall.eth... I think this needs to be addressed at least in requested names. Here's pictures for references: 
https://i.imgur.com/15DjRDN.png (namebazaar request page)
https://i.imgur.com/kVh0ZLp.png  (only domains with 7+ char count can be created)

I suggest that words with less than 7 characters shouldn't be seeable. 
https://i.imgur.com/np9Igw3.png (In this case clicking enter should pop an error message saying the char count is less than 7)

If I remember correctly, the char count limitation will be decreased to 4 chars in the future, but there's still a lot time before that. Therefore, NameBazaar is misleading in this sense, so I feel this should be addressed in the following commits and fixed.

**Comment by madvas** [comment]
This feature has been added
