### ISSUE TITLE
Delete offer ?

### ISSUE THREAD

**Issue by bbbcs** [district0x/name-bazaar#79]
I have one domain listed for both auction and buynow, how do I delete one ? 
Actually one of them has ownership issues as the transfer was done via the other one. Is this why the domain is not listed in the search area ?

**Comment by madvas** [comment]
Currently we don't have delete feature. Let me take a look, what's the name you're trying to offer?

**Comment by bbbcs** [comment]
block-1.eth

**Comment by madvas** [comment]
Yeah, so 1 offering is currently active https://namebazaar.io/name/block-1.eth .
It is displayed in search, but you must uncheck Exclude special char. , as it contains dash

**Comment by bbbcs** [comment]
ok. thanks!

**Comment by madvas** [comment]
I see 2 created offerings https://namebazaar.io/name/potcoin.eth , but neither of them has ownership transferred.

**Comment by nrhirsch** [comment]
yes because when I transfer ownership to one, it leaves the other saying I still need to transfer ownership and the button to do so is inoperative.   I need one deleted or else it fixed so that when you transfer from one, it will do it for both.  system doesn't check uniqueness and should.

**Comment by madvas** [comment]
We'll add deleting later, but you don't need to care about that. Just transfer ownership to one and that one will be displayed in search results. Of course you can't transfer ownership to both, that's why it's disabled for the other one after you transfer it.

**Comment by nrhirsch** [comment]
when you add deleting, let me know.   I'm not going to risk anything on this beta site.  I like it but it's not ready for prime time.

**Comment by madvas** [comment]
Deleting feature has been added

**Comment by nrhirsch** [comment]
Good. I'll try it again and if good will add some great names/domains.
Thanks and quick work! 
--Norman

**Comment by nrhirsch** [comment]
Matus:  Just added 20 names to your site or about 1/3 of what I would add.  Let’s see how these do!   Thanks,

--Norman
