### ISSUE TITLE
My Bids / User's Bids Page

### ISSUE THREAD

**Issue by madvas** [district0x/name-bazaar#8]
![my bids](https://user-images.githubusercontent.com/3857155/29237093-0a4e883e-7f41-11e7-9fa4-a2b7e36b2d6e.png)

**Comment by puttersworth** [comment]
This might be an unnecessary/luxury function at this time, but what about having an "Auto-increase my bid up to a user-defined total/maximum amount".  This way they could just set their highest bid and not have to constantly re-bid when someone else out-bids them. Obviously this amount would have to <= the total amount of ETH they have available.

**Comment by madvas** [comment]
yeah, probably not suitable for first versions. It's important to realise security risks involved in this. Normally user must use password to sign every transaction. So that means user would have to transfer more funds somewhere, from which transactions would be triggered in non-trustless way. Which makes it big target for attacks. But still, in future I can imagine us adding this if there's big enough demand for it. We'll figure out way how to make it reasonably secure.

**Comment by imdying** [comment]
I suggest a show in usd option and an autobid option will stop auction "sniping", but do understand the security implications of this...

What is time extension? Is that how long the auction extends each time a bid is made?

**Comment by madvas** [comment]
For example time extension of 1 hour: If new highest bid arrives less than 1 hour before auction end time, the auction will be extended by another 1 hour. 
That is form of protection for auction sniping

**Comment by imdying** [comment]
great. I like this idea.
