### ISSUE TITLE
Name Details Page

### ISSUE THREAD

**Issue by madvas** [district0x/name-bazaar#9]
![name details](https://user-images.githubusercontent.com/3857155/29237097-28943802-7f41-11e7-896f-d9a0c5873727.png)

**Comment by mediolateral** [comment]
looks good!

**Comment by puttersworth** [comment]
Another potential, in-the-future, addition would be to have a reputation rating attached to the owner/seller.  Buyers would appreciate this because they would have more confidence the seller isn't the fishy/scammer-type, even if operating in a trust-less blockchain environment...

**Comment by madvas** [comment]
There's no real need I for this I think. As transfers are smart-contract based, there's 0 chance of being scammed.
